### ISSUE TITLE
Add land masking to 1 degree case

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/mppnccombine-fast#10]
Need to add land masking to 1 degree test case and check code works.

**Comment by aidanheerdegen** [comment]
Need cases with > 1 time record to test for proper infill of missing values (which mppnccombine does not do correctly)

Need a masked case to check what happens with missing lat/lon dimensions (again mppncombine does not handle this)

Need case with inconsistent chunking to test this functionality.

**Comment by ScottWales** [comment]
Requires test input to check

**Comment by aidanheerdegen** [comment]
Fixed with this https://github.com/coecms/mppnccombine-fast/pull/15
