### ISSUE TITLE
Make backwards compatible

### ISSUE THREAD

**Issue by aidanheerdegen** [coecms/mppnccombine-fast#11]
Does mppnccombine-fast need to accept all current legal command line options, and have the same default behaviour output file behaviour as current mppnccombine?

The advantage of this approach is it can be a drop in replacement with no other modifications. It should issue deprecation warnings that some options are a no-op and will be removed in the future.

An advantage of not doing this, and having a "breaking release" is that it forces people who want to use it to change their run scripts (e.g. payu) to support a new mppnccombine-fast program, and means this program doesn't have to carry crufty baggage from another codebase.

**Comment by aidanheerdegen** [comment]
Options we need

-r : remove files when collation successful
-f : force combine even if some input files missing (? not necessary?)
-v : verbose output (progress info)
-n : Input filename extensions start with number #### instead of 0000.
-m Initialize output variables with a "missing_value" from the variables of the first input file instead of the default 0 value (? not necessary?)
-d : set compression level
-s : toggle shuffle off

Don't overwrite output file?

**Comment by ScottWales** [comment]
My thoughts:
 * -r - sure, can add
 * -f - tool already does this
 * -v - sure
 * -n - currently the tool just uses shell globbing
 * -m - attributes should already come from the first file
 * -d - breaks the fast path, since you need to recompress the data, but can add
 * -s - is this actually used? otherwise like -d

**Comment by aidanheerdegen** [comment]
So what about the first comment? Do we care to support old stuff? Maybe it is better to not do this in light of the possibility of someone selecting an option that will stop this new program from actually working in a fast way?

`-r` this needs to be VERY conservative and only delete the originals if we're damn sure the collation was successful

`-v` is what is does currently, maybe just wrap a fair bit of the current output in `if verbose` blocks.

Options we should probably not support then:

`-n` payu uses a file list, so not currently used by any payu peeps.

`-m` should be a no-op if we support, so probably drop.

`-d`, `-z` and `-s` can break the fast path. Probably drop them, compress by default and use whatever the compression is already. If people want to change the compression level they can do so afterwards with another program

**Comment by ScottWales** [comment]
I think we should try to match the basic functionality, but it needn't be a one to one match. For instance dealing with `-m` and the numbered input files seems a bit of a hassle when either globs with `*` or `{0010..0999}` have the same behaviour. I also personally prefer having the output file distinguished by a `-o` flag so you're not worrying if it should be at the beginning or the end.

An option I just thought of would be to have an extra flag needed to enable the slow path, so if you really needed you could run `-d 8 --slow` or something.

**Comment by aidanheerdegen** [comment]
The `--verbose` option appears to be a no-op (same amount of output)

```
$ wc -l log log.verbose 
   725 log
   725 log.verbose
```

**Comment by aidanheerdegen** [comment]
When I specify a different deflate level it works, but the output doesn't say the aligned copy is slow
```
        Aligned HDF5 copy of geolon_t from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0018
        Aligned HDF5 copy of geolat_t from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0019
        Aligned HDF5 copy of sst from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0018
        Aligned HDF5 copy of geolon_t from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0019
        Aligned HDF5 copy of sst from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0019
        Unaligned (slow) NetCDF4 copy of geolat_c from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0020
        Unaligned (slow) NetCDF4 copy of geolon_c from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0020
        Unaligned (slow) NetCDF4 copy of geolat_t from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0020
        Unaligned (slow) NetCDF4 copy of geolon_t from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0020
        Unaligned (slow) NetCDF4 copy of sst from /short/v45/aph502/mom/archive/test-mom-sis-10-tiles/output000/ocean_daily.nc.0020
```

**Comment by aidanheerdegen** [comment]
As we're not supporting useless/deprecated options, I think `-s/--shuffle` should enforce shuffle, with a corresponding `--no-shuffle`. I have confirmed that the current `-s` option turns off shuffle.

As above, the output does not indicate that the copy is slow when this is turned on.

**Comment by aidanheerdegen** [comment]
Currently the files are output as 
```
:_Format = "netCDF-4" ;
```
I would prefer if they are `NETCDF4_CLASSIC`
```
:_Format = "netCDF-4 classic model"
```

**Comment by aidanheerdegen** [comment]
Insisting on the `-o` option is problematic. This is not how `mppnccombine` is invoked with `payu`, so to support this we'd have to change `payu`, and then somehow detect which `mppnccombine` is being used to support the correct invocation.

**Comment by aidanheerdegen** [comment]
`-r` works, but when testing it I noticed this strange error with `-s` (which combined with `-r` will create corrupted output and delete the originals)

```
$ pwd
/short/v45/aph502/collate_tenth
$ time mpirun -n 4 /home/502/aph502/code/c/mppnccombine-fast/mppnccombine-fast --force -s --output output_1deg_io_layout.nc tmp/ocean_daily.nc.000*
```
produces this nice data:
![screen shot 2018-09-12 at 2 36 55 pm](https://user-images.githubusercontent.com/6063709/45402502-565d3280-b699-11e8-8209-ccdd6536ee0e.png)

If I run the command again it produces this corrupted data

![screen shot 2018-09-12 at 2 38 32 pm](https://user-images.githubusercontent.com/6063709/45402565-8d334880-b699-11e8-87bd-643d28287f12.png)

The same does not happen if I don't use the `-s` option

**Comment by ScottWales** [comment]
Thanks @aidanheerdegen 

* The individual field copy messages now use the logging function, so `--verbose` will turn them on, otherwise they won't show up
* Error message when no `--force` and output file is present has been improved
* Deflate and shuffle options now work and don't corrupt the output
* Added '--shuffle' argument, removed '-s' short flag rather than have it swap meaning
* Rather than add a `--slow` flag I've put the slow copy message as a warning, so it will show for each unaligned/different compression field unless you use `--quiet`

Changing to classic format requires swapping into and out of define mode, better to have that as a separate ticket

**Comment by aidanheerdegen** [comment]
```Usage: mppnccombine-fast [OPTION...]
Quickly collate MOM output files
```
Doesn't properly tell users how to invoke the program. Should be something like:
```
Usage: mppnccombine-fast [OPTION...] <files>
Quickly collate MOM output files, where <files> should be a list of files, which can be generated by a shell glob or similar
```

**Comment by aidanheerdegen** [comment]
Confirmed multiple invocations of `--shuffle` on existing output file no longer produces corrupted output.

**Comment by aidanheerdegen** [comment]
Confirmed `--verbose` produces more output than without that option. 

`--quiet` and `--verbose` produces the same as `--quiet`. Just checking that is as intended.

For small files this output:
```
Total compressed size 0.00 GiB | 0.00 GiB / sec
```
is not informative.

**Comment by aidanheerdegen** [comment]
Confirm the better output if `--force` is not specified and output exists
```
[rank 000] ERROR: Output file 'output_1deg_io_layout.nc' already exists (try --force)
```

**Comment by aidanheerdegen** [comment]
Can we use something like this to suppress multiple outputs from `argp`

http://agentzlerich.blogspot.com/2011/01/using-argp-with-mpi-based-applications.html

**Comment by ScottWales** [comment]
Help info is now only printed on rank 0
```
Usage: mppnccombine-fast [OPTION...] --output=OUTPUT INPUT [INPUT ...]

Quickly collate MOM model files

Gathers the INPUT MOM model files (provided e.g. with a shell glob) and joins
them along their horizontal dimensions into a single NetCDF file

  INPUT                      Input NetCDF file
  -o, --output=OUTPUT        Output NetCDF file
  -f, --force                Combine even if output file present
  -r, --remove               Remove the input files after completion
  -d, --deflate=[0-9]        Override compression level (slower)
      --shuffle              Force enable shuffle filter (slower)
      --no-shuffle           Force disable shuffle filter (slower)
  -v, --verbose              Be verbose
  -q, --quiet                Be quiet (no warnings)
      --debug                Debug info
  -?, --help                 Print this help list

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
```

**Comment by aidanheerdegen** [comment]
Only outstanding issue is the `-o` requirement. I know it is nice to have, but I would like to support the old behaviour otherwise it is a royal PITA to change with `payu`, and still support the old `mppnccombine`, which people might want to do if they have netCDF3 files.

Can the program check for `-o` and use it if it exists, otherwise fall back to using the first file in the command line arguments?

**Comment by aidanheerdegen** [comment]
Scratch that. Realised we'll need a wrapper script in the first instance anyway, so can have the path expected behaviour for the wrapper and use -o internally.
