### ISSUE TITLE
collating thousands of tiles fails: Argument list too long

### ISSUE THREAD

**Issue by aekiss** [coecms/mppnccombine-fast#24]
Thanks for this fast collation method, it's a huge improvement.

However one issue is in collating regional outputs, which are written as one file per rank regardless of io_layout, so can be very numerous. In ACCESS-OM2-01 I'm saving a 3d variable at one level globally, which at 0.1 deg produces 4357 tiles. In this case mppnccombine-fast fails with error "Argument list too long".

An example log file is 
`/short/v45/aek156/access-om2/archive/01deg_jra55_iaf/pbs_logs/01deg_jra55_i_c.e1953836`

**Comment by ScottWales** [comment]
Thanks for the report @aekiss 

In investigating the issue I also found a problem where input files weren't being properly closed, which can result in files only being partially collated

**Comment by aekiss** [comment]
I presume that non-closing issue results in abnormal termination (rather than producing an apparently-collated file with missing data)?
