### ISSUE TITLE
Record dimension appears to be destroyed.

### ISSUE THREAD

**Issue by russfiedler** [coecms/mppnccombine-fast#26]
It looks like the record dimension is converted into a fixed dimension.  This is not a good thing...

**Comment by ScottWales** [comment]
Thanks Russ, should be easy to fix

**Comment by russfiedler** [comment]
Good, I was worried that unlimited dimensions may cause problems and you had to do a conversion to do everything in place.

**Comment by ScottWales** [comment]
@russfiedler I've put a version of mppnccombine-fast that handles unlimited dimensions on Raijin at `/short/public/saw562/mppnccombine-fast-unlim`

Can you please check that this behaves as you expect it to?

Thanks, Scott

**Comment by ScottWales** [comment]
Thanks, I've updated the version in my public directory with a fix

**Comment by russfiedler** [comment]
@ScottWales  We've spotted that no data is written for the bottom 18 levels in the 75 level model. It has a vertical chunksize of 19. 3*19+18.

**Comment by aidanheerdegen** [comment]
I have confirmed these are fixed in https://github.com/coecms/mppnccombine-fast/pull/33
